### ISSUE TITLE
[FEATURE]  getSymbolPeriods on the past

### ISSUE THREAD

**Issue by dawadam** [Reiryoku-Technologies/Mida#106]
Many exchanges (Binance) offer to retrieve OHLC data far in the past (from the origin of the market), also in 1 minute time frame.

It would be handy to be able to do this with "getSymbolPeriods".

On documentation:

`getSymbolPeriods (symbol: string, timeframe: number): Promise<MidaPeriod[]>;`

Maybe can be :

`getSymbolPeriods (symbol: string, timeframe: number, from: number, to: number): Promise<MidaPeriod[]>;`

**Comment by dawadam** [comment]
I see on cTrader open API documentation, it's also possible to fetch past data :

https://help.ctrader.com/open-api/symbol-data/#historical-bars-data

**Comment by Vasile-Peste** [comment]
This feature has been delivered (check https://github.com/Reiryoku-Technologies/Mida/issues/132)

Thank you,
Vasile

**Comment by dawadam** [comment]
I think it' a mistake.
Historical trades and orders are not candlestick (OHLC) data.
