### ISSUE TITLE
expirationDate is undefined 

### ISSUE THREAD

**Issue by vitalizis** [Reiryoku-Technologies/Mida#118]
I create order next way:

```
    const myOrder = await myAccount.placeOrder({
        symbol: 'EURUSD', 
        direction: MidaOrderDirection.BUY,
        volume: 0.1,
        limit:1.078,
        protection: {
            stopLoss: 1.075, 
            takeProfit: 1.083, 
        },
        expirationDate: date().addMinutes(5),
    });
```

It doesn't create expirationDate property
console.log(myOrder.expirationDate); //undefined

1. I try put inside expirationDate different values using native JS, not only from @reiryoku/mida. It doesn't matter
2. I use "^2023.5.0" version

**Comment by Vasile-Peste** [comment]
Hello! May I ask what trading platform are you using so we can help you?

Thank you!

**Comment by vitalizis** [comment]
> Hello! May I ask what trading platform are you using so we can help you?
> 
> Thank you!

Hi! Thank you for replay. I use cTrader for trading

**Comment by Vasile-Peste** [comment]
I understand, in this case it should be because time in force is not being set to good till date.

Reference
https://www.mida.org/documentation/orders/place-order.html#time-in-force

Example
```javascript
    const myOrder = await myAccount.placeOrder({
        symbol: 'EURUSD', 
        direction: MidaOrderDirection.BUY,
        volume: 0.1,
        limit:1.078,
        protection: {
            stopLoss: 1.075, 
            takeProfit: 1.083, 
        },
        timeInForce: MidaOrderTimeInForce.GOOD_TILL_DATE,
        expirationDate: date().addMinutes(5),
    });
```

Please let me know if it works as expected

**Comment by vitalizis** [comment]
> ```js
>  timeInForce: MidaOrderTimeInForce.GOOD_TILL_DATE,
> ```

it works excellent, thank you very much!

**Comment by vitalizis** [comment]
> I understand, in this case it should be because time in force is not set to good till date.
> 
> Reference https://www.mida.org/documentation/orders/place-order.html#time-in-force
> 
> Example
> 
> ```js
>     const myOrder = await myAccount.placeOrder({
>         symbol: 'EURUSD', 
>         direction: MidaOrderDirection.BUY,
>         volume: 0.1,
>         limit: 1.078,
>         protection: {
>             stopLoss: 1.075, 
>             takeProfit: 1.083, 
>         },
>         timeInForce: MidaOrderTimeInForce.GOOD_TILL_DATE,
>         expirationDate: date().addMinutes(5),
>     });
> ```
> 
> Please let me know if it works as expected

It works excellent, thank you very much!

**Comment by Vasile-Peste** [comment]
Happy to hear that, I'll close the issue
