### ISSUE TITLE
Market Components example

### ISSUE THREAD

**Issue by karstenjakobsen** [Reiryoku-Technologies/Mida#120]
First of all - thank you for this awesome project!

```
"Trading systems are used under the hood to regulate and execute market components. It's recommended to use the Market Component API over the Trading System API as it allows to quickly develop and maintain an idea in a declarative way."
```

Second - since Market Components are preferred over Trading System API , could your provide a full example of a running service with this structure?

**Comment by Vasile-Peste** [comment]
Hello! Here is an article that covers some of the most important aspects and API
https://www.mida.org/posts/reactive-programming-in-financial-markets/

By the end of this month we plan to update the documentation with the full API and usage examples

Thank you!
