### ISSUE TITLE
Historical Trades and Orders

### ISSUE THREAD

**Issue by desoss** [Reiryoku-Technologies/Mida#132]
Is it possible to get a list of trades and orders older than the most recent ones, currently obtained by doing `myAccount.getOrders` or `myAccount.getTrades`?

**Comment by Vasile-Peste** [comment]
Hello! Getting orders and trades within a specific timeframe it's not currently possible, but a historical API is being planned as follows

```
class MidaTradingAccount {
    getOrdersHistory (fromTimestamp: number, toTimestamp: number, symbol: string): Promise<MidaOrder[]>;
    getTradesHistory (fromTimestamp: number, toTimestamp: number, symbol: string): Promise<MidaTrade[]>;
    getPeriodsHistory (fromTimestamp: number, toTimestamp: number, symbol: string, timeframe: number): Promise<MidaPeriod[]>;
    getTicksHistory (fromTimestamp: number, toTimestamp: number, symbol: string): Promise<MidaTick[]>;
}
```

We should deliver it by the end of this month!

**Comment by Vasile-Peste** [comment]
Hello, this feature has been delivered with [Mida 2023.10](https://github.com/Reiryoku-Technologies/Mida/releases/tag/v2023.10.0)!

This usage example returns all the orders between 20 May 2023 - 25 May 2023, please note that on cTrader the maximum time range is 1 week, send multiple requests if you need to fetch longer time ranges
```javascript
import { date, } from "@reiryoku/mida";

const fromTimestamp = date("2023-05-20").timestamp;
const toTimestamp = date("2023-05-25").timestamp;

console.log(await myAccount.getOrdersHistory(fromTimestamp, toTimestamp));
```

Feel free to open another issue if you have any issue

Thank you,
Vasile
