### ISSUE TITLE
cTrader read label from open trades

### ISSUE THREAD

**Issue by UsernameGitiHub** [Reiryoku-Technologies/Mida#135]
does anybody have a idea why my following code does not show me the label which i have in the open trade written? When i look in the webapp i see the open trade have that label

![picture](https://github.com/Reiryoku-Technologies/Mida/assets/36551485/8ec3fbfc-6f5a-4e65-9ffb-851f84e45475)

const allPositions = await myAccount.getOpenPositions(); console.log(allPositions);
for (const position of allPositions)
{
  console.log("========================");
  console.log("Position:", position);
  console.log("Ticket:", position.label);
  console.log("Ticket:", position.id);
  console.log("Symbol:", position.symbol);
  console.log("Volume:", position.volume);
  console.log("Entry Price:", position.entryPrice);
}

but console.log("Ticket:", position.label); is showing me "undefined" why the open trade have the label why the function does not give it me?

**Comment by Vasile-Peste** [comment]
Hello!

A position doesn't have a label, since many orders and trades can affect a position, this means a position should have many labels.

You can check if an order or trade that affected that position has a label.

```
const allPositions = await myAccount.getOpenPositions();

for (const position of allPositions) {
    const orders = await myAccount.getOrders(position.symbol);
    const label = orders[0].label;

    console.log(label);
}
```

Here we take the label of the first order affecting the position but there may be other orders with more labels, depending on your logic.

**Comment by UsernameGitiHub** [comment]
You can see in the following picture i have 2 trades open, ok ctrader call them position i dont know why, but for me this are 2 trades in EURUSD and you can see in the picture the trades have a label:

![picture](https://github.com/Reiryoku-Technologies/Mida/assets/36551485/4e997800-41b2-4bf6-a0e5-aad17f31f320)

and now i try from your example code the following:

`for (const position of allPositions)
{
  console.log("========================");
  console.log("Position:", position);
  
  const myPosition = position;
  const orders = await myAccount.getOrders(myPosition.symbol);

	for (const order of orders) {
		if (order.positionId === myPosition.id) {
			 const label = order.label;

			 console.log("label "+label);
		}
	}
  
  console.log("Ticket:", position.label);
  console.log("Ticket:", position.id);
  console.log("Symbol:", position.symbol);
  console.log("Volume:", position.volume);
  console.log("Entry Price:", position.entryPrice);
}
`

and it dont work, please show me exactly how can i read the labels for this 2 open trades or call them position or order i dont know, but would be nice to see if this is possible

**Comment by Vasile-Peste** [comment]
Labels are stored on orders, if you need to get a position by label and you have the position id, get the orders and filter them by position id, then you can access the label

https://www.mida.org/documentation/orders/order.html
https://www.mida.org/documentation/orders/get-orders.html

Let me know if you need more help!

Thank you,
Vasile

**Comment by vanillamasonry** [comment]
In fact is working only in the current session
If you kill the session after you place an order, login again with Mida.login and you try to get order.positionId you will have an empty string. <- Here is the real problem

**Comment by UsernameGitiHub** [comment]
i have find a way to read the labels:

for(let c=0; c<Currencys.length; c++)
{
   const orders = await myAccount.getOrders(Currencys[c]);
   for(const order of orders)
	{
		if(order.label != null && order.isExecuted==true)
		{		
			console.log("order.isOpening "+order.isOpening);
			console.log("Order ID:", order.id);
			console.log("Order orderId:", order.orderId);
			console.log("Order positionId:", order.clientOrderId);
			console.log("Order label:", order.label);
			console.log("Order direction:", order.direction);
			console.log("Order executed:", order.isExecuted);
			console.log("Order symbol:", order.symbol);
        }		
	}
}

now i am looking for a function how i can close a open trade, which function must i use? in the sdk docs i see just one function close() and i dont know how to use that

**Comment by Vasile-Peste** [comment]
> i have find a way to read the labels:
> 
> for(let c=0; c<Currencys.length; c++) { const orders = await myAccount.getOrders(Currencys[c]); for(const order of orders) { if(order.label != null && order.isExecuted==true) { console.log("order.isOpening "+order.isOpening); console.log("Order ID:", order.id); console.log("Order orderId:", order.orderId); console.log("Order positionId:", order.clientOrderId); console.log("Order label:", order.label); console.log("Order direction:", order.direction); console.log("Order executed:", order.isExecuted); console.log("Order symbol:", order.symbol); } } }

Good job!
