### ISSUE TITLE
ERROR IN PRODUCTION

### ISSUE THREAD

**Issue by eritondev-stack** [Reiryoku-Technologies/Mida#23]
Hello guy, how are you?

Can you help me?

Method  marketWatcher.on("tick", (event:).... not working in production, not reveive information symbols.

**Comment by Vasile-Peste** [comment]
> Hello guy, how are you?
> 
> 
> 
> Can you help me?
> 
> 
> 
> Method  marketWatcher.on("tick", (event:).... not working in production, not reveive information symbols. 
> 
> 

Hello, can I see all your code? I need to understand the context and environment. Thank you!

**Comment by eritondev-stack** [comment]
`async function startOnSymbols(symbol: any, myAccount: MidaBrokerAccount) {

    const marketWatcher = new MidaMarketWatcher({ brokerAccount: myAccount });
    try {
        await marketWatcher.watch(symbol, { watchTicks: true, });

        marketWatcher.on("tick", (event: any) => {
            const { tick, } = event.descriptor;
            const isExist = allPairs.filter(item => item.symbol === symbol).length > 0
            if (isExist) {
                //console.log('Ja existe por favor atualizar')
                const objIndex = allPairs.findIndex((obj => obj.symbol === symbol));
                allPairs[objIndex].price = Number(tick.bid)

            } /* else {
                allPairs.push({
                    symbol: symbol,
                    price: Number(tick.bid)
                })
            } */
            //console.log(symbol + ': ' + tick.bid);
            global.SocketServer.emit('CTRADER', allPairs)
        });
    } catch (e) {
        console.log(e)
    }
}
`
Localhost work ok, but in production not receive informations symbol.

**Comment by eritondev-stack** [comment]
I found the error, I had a method in my class that exceeded 50 requests per second, and it wasn't going through onTick. Thank you for your help.
