### ISSUE TITLE
Last live candle

### ISSUE THREAD

**Issue by dbvcode** [Reiryoku-Technologies/Mida#25]
Is it possible to get the last LIVE candle for the 5m chart for instance from cTrader(Pepperstone)?
I understand that there is an event for getting the last closed candle, and also the tick data.
There is a way(not best) to create the last candle from the tick data in a 'live' form, but is something like this already available from the broker? Or what are your suggestions for needing to execute market orders that depend on the live candle(to compute indicators).

Thanks

**Comment by Vasile-Peste** [comment]
Hi, currently there is no direct way to retrieve the last live candle. But I understand the importance of this feature so I'm thinking to implement it in the `MarketWatcher` API as an event named `period-update`, I will keep you updated about the progress in this issue.

Meanwhile there is a solution: Mida exposes a (currently undocumented) utility function named `composePeriods()`. This function creates candlesticks from a set of ticks. Basically if we pass for example 1000 ticks we could easily retrieve their candlesticks representation on any timeframe.

The `composePeriods()` function takes 3 arguments
 - The ticks array
 - The start date to start composing the periods
 - The timeframe, so candles will be composed starting from startDate + timeframe

Here's how it works, let's suppose we want to know the last live M5 candlestick as you have requested
```javascript
import { composePeriods, } from "@reiryoku/mida";

let m5Ticks = [];

marketWatcher.on("tick", (event) => {
    m5Ticks.push(event.descriptor.tick);

    const lastLiveCandle = composePeriods(m5Ticks, m5Ticks[0].date, MidaTimeframe.M5)[0];
});

marketWatcher.on("period-close", (event) => {
    const candle = event.descriptor.period;
    
    if (candle.timeframe === MidaTimeframe.M5) {
        // Candlestick has been closed so empty the last live candle ticks
        m5Ticks = [];
    }
});
```

Note that you need to execute the code above when a M5 candlestick is closed in order to synchronize the captured ticks with the M5 timeframe, I don't have fully tested the code above so let me know if you have any problem

I will keep this issue open until we implement a direct event-driven way to retrieve the last live candlestick

**Comment by dbvcode** [comment]
Thank you for your reply!
I will try and let you know.
Great project you put together here, I'm very happy I got to it and you seem to be quite involved in it!

**Comment by dbvcode** [comment]
Ok, I've taken out of the latest Mida `composePeriods` to see how it works.
It works very good!
However, I've created an array of candles/periods that I put out on a chart to see it checks with cTrader.

The process I use is:
1. Get the existing closed candles with `getSymbolPeriods`
2. Create live(tick based) last candle
3. Switch the live closed candle with the one from "period-close" event when that happens

My model to store the data is a key pair value:
```
  export interface Kline {
    [key: string]: {
      open: string;
      high: string;
      low: string;
      close: string;
      volume: string;
    }
  }
```

I've found 2 things:
1. When you start the tick stream in your example the second and milliseconds are what they are on the first tick and they are used for creating the next ones from what I see. The issue I have is I need a clean 0 second and 0 millisecond timestamp(startDate) on the candles so I update the key values in my key:pair object match.

So I tweaked the version you suggested:
```
marketWatcher.on("tick", (event) => {
    m5Ticks.push(event.descriptor.tick);
    const firstTickDate = dateToLuxon(m5Ticks[0].date.valueOf()).set({ second: 0, millisecond: 0 }); //I am using Luxon but the idea is to clear the millisecond and second
    const midaDate = new MidaDate(firstTickDate.valueOf());
    const lastLiveCandle = composePeriods(m5Ticks, midaDate, MidaTimeframe.M5)[0];
});
```
This way the candle startDate is consistent with the one from `period-close` and the one from `getSymbolPeriods`

3. The second issue is that the `period-close` event is coming **a few seconds after** the timestamp change. This in turn has 2 issues:
  a. Clearing the `m5Ticks = [];` on the `period-close` can loose ticks that are from the NOW timeframe
  b. For some reason is duplicating the last candle with the data from the one before for a short while(until `m5Ticks` is cleared I think)
The solution for me is to check if the startDate has changed since the last `composedPeriod` and filter only the ticks that are bigger of equal than that value.
```
let m5Ticks: MidaSymbolTick[] = [];
let lastTs = NaN;
marketWatcher.on("tick", (event) => {

  m5Ticks.push(event.descriptor.tick as MidaSymbolTick);
    
  const firstTickDate = dateToLuxon(m5Ticks[0].date.valueOf()).set({ second: 0, millisecond: 0 });
  const midaDate = new MidaDate(firstTickDate.valueOf());
  
  
  let lastLiveCandle = composePeriods(m5Ticks, midaDate, MidaTimeframe.M1)[0];
  if (lastLiveCandle.startDate.valueOf() !== lastTs) {
      m5Ticks = m5Ticks.filter(t => t.date.valueOf() >= lastLiveCandle.startDate.valueOf());
      lastTs = lastLiveCandle.startDate.valueOf();
      
      lastLiveCandle = composePeriods(m5Ticks, midaDate, MidaTimeframe.M1)[0];
  }
)}
```
This seems to work fine and the candles change in a nice fashion and they also seem to look like the ones from cTrader.

On the period-close event the only thing I do is rewrite the candle that I get, as I assume it's from the broker so it's good.

All of this is very close to reality. Obviously if you miss a tick the data is off, but hopefully not an issue.

I played with 1m timeframe but in bigger timeframes I think it's a good idea for instance for 5m candles to watch the candle-close on the 1m and add it in the tick data just to be sure the data is not missing if you miss ticks.

I hope this helps.

**Comment by Vasile-Peste** [comment]
Hey, with
[Mida 2022.1](https://github.com/Reiryoku-Technologies/Mida/releases/tag/v2022.1.0) and [Mida cTrader 5](https://github.com/Reiryoku-Technologies/Mida-cTrader/releases/tag/v5.0.0)
now there is the `onPeriodUpdate` event and hook!

Example
```javascript
import { MidaTimeframe, } from "@reiryoku/mida";

await marketWatcher.watch("EURUSD", {
    watchPeriods: true,
    timeframes: [ MidaTimeframe.M5, ],
});

marketWatcher.on("period-update", (event) => {
    const candle = event.descriptor.period;
});
```

Let me know if it works as expected for you!

**Comment by dbvcode** [comment]
Just saw this was assigned to me!
I am using the Mida with the MidaDecimal.min and max error so the candle is not good.
Does it use the composeCandle under the hood?

**Comment by Vasile-Peste** [comment]
> Just saw this was assigned to me!
> I am using the Mida with the MidaDecimal.min and max error so the candle is not good.
> Does it use the composeCandle under the hood?

It's not using compose candle, and it's a separate event that will directly provide you the last live candle.

```
marketWatcher.on("period-update", (event) => {
    const liveCandle = event.descriptor.period;
});
```

**Comment by dbvcode** [comment]
Works like a charm!
And indeed it works with Mida 2022.1.0 as well!
Thanks a lot for this!
