### ISSUE TITLE
Live account info

### ISSUE THREAD

**Issue by dbvcode** [Reiryoku-Technologies/Mida#27]
Is there any way to get live account info?
EventEmitter or websocket like?
When an order is executed in cTrader for instance to get the event in Mida.

**Comment by Vasile-Peste** [comment]
You should be able to just listen an order event on your trading account instance

```javascript
myAccount.on("order", (event) => {
    const order = event.descriptor.order;
});
```

But this works only with the next version of Mida cTrader which is going to be released by end of this week.

**Comment by Vasile-Peste** [comment]
[Mida cTrader 3.0.0](https://github.com/Reiryoku-Technologies/Mida-cTrader/releases/tag/v3.0.0) is out and supports this events, let me know if everything works as expected for you. There are some small changes in the API so please check the updated documentation at https://www.mida.org.

You can also listen to trades being executed
```javascript
myAccount.on("trade", (event) => {
    const trade = event.descriptor.trade;
    
    console.log(trade.orderId);
    console.log(trade.positionId);
    console.log(trade.grossProfit);
});
```

**Comment by dbvcode** [comment]
THIS WORKS! So cool!
Thanks

**Comment by dbvcode** [comment]
Btw, what is a trade?
I watched the event but didn't see anything.
I see in cTrader an order is a pending order, a positions is an executed order and a trade is a position that's closed either with take profit or stop loss?

**Comment by Vasile-Peste** [comment]
> Btw, what is a trade?
> I watched the event but didn't see anything.
> I see in cTrader an order is a pending order, a positions is an executed order and a trade is a position that's closed either with take profit or stop loss?

As you probably know everything revolves around `orders`, `trades` and `positions`.

An order is the intention to buy or sell an asset. An order is processed by the trading platform according to the client directives and is finalized with the execution of one or more trades (cTrader calls them deals).

A trade (or deal) is the result of an order execution and represents the transaction occurred to entirely or partially fill the order requested volume. An order can be executed entirely or partially with one or more trades.

An open position represents a volume of asset held by the account.
