### ISSUE TITLE
REQUEST_FREQUENCY_EXCEEDED on getOrders()

### ISSUE THREAD

**Issue by dbvcode** [Reiryoku-Technologies/Mida#28]
This is funny. If I run a getOrders() on Pepperstone with cTrader I instantly get:
```
{
  payloadType: 'PROTO_OA_ERROR_RES',
  ctidTraderAccountId: '0',
  errorCode: 'REQUEST_FREQUENCY_EXCEEDED',
  description: 'You have reached the rate limit of requests',
  maintenanceEndTimestamp: null,
  clientMsgId: 'bef1d2f0-dcc5-11ec-b2d2-0da955e5ed11'
}
```

But other methods work and don't cause this issue. I can assure you it's not a request frequency issue. I just made this call and that's it.

**Comment by Vasile-Peste** [comment]
This is a cTrader limitation, from cTrader Open API (https://spotware.github.io/open-api-docs/proxies-endpoints/) the limitations are:
- 50 requests per second per application for non historical data requests.
- 5 requests per second per application for historical data requests.
- 25 concurrent connections per application.

`getOrders()` is a historical data request, you are making it only one time? You should make maxium 5 calls per second to this kind of methods.

Let me know, otherwise I can ask help to the cTrader team, I also had similar issues before.

**Comment by dbvcode** [comment]
I call it only once and no other call to them.
If I call getSymbolPeriods() there is no issue.
There is something fishy here especially if cTrader is giving this result.

**Comment by Vasile-Peste** [comment]
With the recent updates on `Mida cTrader` the number of requests for getting orders and historical data has been reduced, I think that now it should be less likely to get this error when respecting the rating limit.

**Comment by dbvcode** [comment]
I'm still getting this error with `"@reiryoku/mida-ctrader": "^3.0.1"`

**Comment by dbvcode** [comment]
```
import { Mida, MidaOrder, MidaTrade, MidaTradingAccount } from "@reiryoku/mida";
import { CTraderPlugin } from "@reiryoku/mida-ctrader";
Mida.use(new CTraderPlugin());

let account: MidaTradingAccount = undefined;

export async function initPepperstoneGeneric() {
    account = await Mida.login("cTrader", {
        clientId: "***",
        clientSecret: "***",
        accessToken: "***",
        cTraderBrokerAccountId: "***",
    });

    console.log(await account.getOrders('GER40'));
}

initPepperstoneGeneric().then();
```

**Comment by dbvcode** [comment]
This one is still an issue for me with mida 7.3.0 and mida-ctrader 4.0.0

**Comment by Vasile-Peste** [comment]
Hello, thank you for your patience, could you try again with [Mida 2022.1](https://github.com/Reiryoku-Technologies/Mida/releases/tag/v2022.1.0) and [Mida cTrader 5](https://github.com/Reiryoku-Technologies/Mida-cTrader/releases/tag/v5.0.0)? Let me know if it works! Thank you again.

**Comment by dbvcode** [comment]
It is working! Cool!
What was the problem?

**Comment by Vasile-Peste** [comment]
> It is working! Cool!
> What was the problem?

Honestly I'm not 100% sure, but with the refactoring of the Mida cTrader plugin I have reduced the number of requests sent.
Anyway I'm happy to hear this, I will close the issue.
