### ISSUE TITLE
Add a function / method that helps calculate take profit and stop loss price points on all symbols.

### ISSUE THREAD

**Issue by Georgemburu** [Reiryoku-Technologies/Mida#32]
**Stop Loss and Take Profit calculation for all symbols.**

Have different functions to calculate stop loss and take profit that takes in different arguments.

_Stop Loss Function example:_

`function getStoplossPricePoint(symbol,amountToRisk,lotSize) => {stop_loss_number_of_pips,stop_loss_price_point}`

`function getStoplossPricePoint(symbol,numberOfPipsToRisk,amountToRisk)=>{lot_size_to_use,stop_loss_price_point}`

`function getStoplossPricePoint(symbol,numberOfPipsToRisk,lotSize)=>{amountToRisk,stop_loss_price_point}`

_Take PROFIT Function example:_

`function getTakeProfitPricePoint(symbol,amountToTakeAsProfit,lotSize) => {take_profit_number_of_pips,take_profit_price_point}`

`function getTakeProfitPricePoint(symbol,take_profit_number_of_pips)=>{take_profit_price_point,amount_to_take_as_profit}`

`function getTakeProfitPricePoint(symbol,amountToTakeAsProfit,take_profit_number_of_pips)=>{take_profit_price_point,amount_to_take_as_profit,lot_size_to_use}`

**Comment by Vasile-Peste** [comment]
Hello, thank you for your time.
It is not very clear to me the criteria for deciding a stop loss or take profit behind this.
It mostly depend on the trading strategy and not on the amount to loss.
Can you elaborate it more please?
Thank you!

**Comment by Georgemburu** [comment]
I think a better function to have for as the solution for the issue is this :

Let's say you want to take a trade on gold/usd at the current price which is 1800.00 and you want your stop loss to be 20 pips.

Can you add a function like this :

``` 
// @ params 
// symbol -> the symbols name
// price -> the entry price
// pips -> the amount of pips you want to add to the price
// @ Returns: 
// The price + pips

function addPipsToPrice(symbol:string, price:number, pips:number) {}```


Also have a function:
function substractPipsFromPrice(symbol:string, price:number, pips:number) {}```

// @ returns price - pips


```

**Comment by Vasile-Peste** [comment]
The Mida API is enough to add/sub pips from a price. You can read me about the `pipPosition` property of `MidaSymbol`.
