### ISSUE TITLE
Changing the label field

### ISSUE THREAD

**Issue by ezcafe** [Reiryoku-Technologies/Mida#36]
![Screen Shot 2022-06-16 at 6 42 43 AM](https://user-images.githubusercontent.com/67532045/174077832-fa79f794-6107-49d7-8da4-fd8dcf004bb9.png)

It would be nice if we can change labels when placing new orders.
The use case: We can add, for example, the indicators or the reasons why we opened this order. 
Later, we can use this label to close/cancel the orders.

Thanks

**Comment by Vasile-Peste** [comment]
With
[Mida 2022.1](https://github.com/Reiryoku-Technologies/Mida/releases/tag/v2022.1.0)
[Mida cTrader 5](https://github.com/Reiryoku-Technologies/Mida-cTrader/releases/tag/v5.0.0)
you can now specify the `label` property and value in the order directives,
let me know if it works!

**Comment by Vasile-Peste** [comment]
> Specify the `label` property works very well. Thanks @Vasile-Peste for the quick update.
> 
> ![Screen Shot 2022-07-25 at 7 53 32 PM](https://user-images.githubusercontent.com/67532045/180782332-2d2e399e-0e7e-49f5-8a8a-4dbd43d98124.png)
> 
> Could you please add the API to read `label` property of the open positions as well? 🥰 Thank you

We have just released [Mida cTrader 5.3](https://github.com/Reiryoku-Technologies/Mida-cTrader/releases/tag/v5.3.0) and you can read the label from orders now. This is not exposed on positions since positions are affected by multiple orders therefore it makes more sense to get the orders of a position and then reading their labels.

Thank you!

**Comment by ezcafe** [comment]
Hi @Vasile-Peste,
In the screenshot, I have 2 positions opened by 2 different orders (these orders are made manually, not by code). These positions have their own label. So It makes sense to be able to get the label from position, right?

My use case is: when MACD is crossing up, then I open a position with the label "MACD cross up" to that position. Later, when MACD is crossing down, I will close all the positions with label "MACD cross up".
Is that technically possible?
Thanks

![Screen Shot 2022-09-30 at 7 27 42 PM](https://user-images.githubusercontent.com/67532045/193269452-6fdd5a63-48d0-4a11-b076-5c5697820eec.png)

**Comment by ezcafe** [comment]
![Screen Shot 2022-09-30 at 7 36 10 PM](https://user-images.githubusercontent.com/67532045/193271009-7a50fb33-2df7-4d6a-a2f2-270f036ffcaf.png)

**Comment by ezcafe** [comment]
It's working well.
Thank you very much
