### ISSUE TITLE
Mida instances

### ISSUE THREAD

**Issue by dbvcode** [Reiryoku-Technologies/Mida#46]
IMHO this is a must as there is no way with Mida right now to trade multiple accounts from the same app.

This would be very cool:
```
const accountBinance = new Mida("Binance/Spot",{...});
await accountBinance.login();
console.log(await accountBinance.getBalance());

const accountCTraderLive =  new Mida("cTrader",{...});
await accountCTraderLive.login();
console.log(await accountCTraderLive.getBalance());

const accountCTraderDemo =  new Mida("cTrader",{...});
await accountCTraderDemo.login();
console.log(await accountCTraderDemo.getBalance());
```

Would this be possible as a future development?

**Comment by Vasile-Peste** [comment]
This is currently possible, it's not working for you?

``` javascript
import { login, } from "@reiryoku/mida";

const binanceAccount = await login("Binance/Spot", { ... });
const cTraderAccount = await login("cTrader", { ... });
```

Try creating an empty Mida project by using `npm init mida` in your terminal.

Reference: https://www.mida.org/documentation/essentials/login.html#login

**Comment by dbvcode** [comment]
I thought there is only one instance of Mida with only one account.
Can I do 2 cTrader accounts this way as well?

**Comment by dbvcode** [comment]
Does indeed work!
Sorry to open this ticket, from the examples I saw in the docs I got the impression it's only one account per instance of Mida.
Didn't even try to do it until you said it works!
Cool!
