### ISSUE TITLE
.toNumber() for MidaDecimal

### ISSUE THREAD

**Issue by dbvcode** [Reiryoku-Technologies/Mida#54]
I think MidaDecimal is a very good idea.
But I think it needs a simple method `.toNumber()` that should either return `undefined` if the initial value is undefined or `number` if there is a value.
For now I convert it to a string and then digest it with bignumber.js as I avoid doing `Number(midaDecimal)`

**Comment by Vasile-Peste** [comment]
[PR #55](https://github.com/Reiryoku-Technologies/Mida/pull/55)

**Comment by Vasile-Peste** [comment]
Live with `Mida 2022.2.0`(https://github.com/Reiryoku-Technologies/Mida/releases/tag/v2022.2.0)
