### ISSUE TITLE
marketWatcher.on("period-close"...) emits wrong timeframe

### ISSUE THREAD

**Issue by dbvcode** [Reiryoku-Technologies/Mida#58]
This one used to work for sure, but does not work as it should anymore.

```
marketWatcher.watch(symbol, {
        watchPeriods: true,
        watchTicks: true,
        timeframes: [300] //5m
    });

marketWatcher.on("period-close", (event) => {
        const candle = event.descriptor.period as MidaPeriod;
        console.log('period close',candle.timeframe);
});
```

This one does indeed emit when the 5m candle closes, but the `timeframe` on the candle says `60` instead of `300`.
If I subscribe to multiple timeframes they all say they are 60.

**Comment by Vasile-Peste** [comment]
It looks like a bug on cTrader Open API, I have reported it to them

**Comment by Vasile-Peste** [comment]
I think they need some time to fix on their side so I have applied a fix on our side by just setting the timeframe to the requested one instead of decoding it from the response. Just update to [Mida cTrader 5.0.2](https://github.com/Reiryoku-Technologies/Mida-cTrader/releases/tag/v5.0.2).
