### ISSUE TITLE
Adding a custom id to a MidaTradingAccount

### ISSUE THREAD

**Issue by thijserven** [Reiryoku-Technologies/Mida#74]
Is there a way to add a custom id to a MidaTradingAccount when using Mida.login()?

The MidaTradingAccount class does have an id property but it's set as read only so I can't assign any value to it. Is this intentional?

**Comment by Vasile-Peste** [comment]
Hello, the `id` field of `MidaTradingAccount` is supposed to contain the trading account id in the trading platform. So it's intentional to be a read only property. But if you want to assign an id to your trading account you have plenty of ways to do this. For example:

```javascript
const ids = new WeakMap();
const myAccount = ...

ids.set(myAccount, "id");
```

What do you think?

**Comment by thijserven** [comment]
Thanks! Never heard of WeakMaps before but it provided the solution for me.

**Comment by thijserven** [comment]
Also one side note I noticed that the MIdaTradingAccount id of a Binance/Spot account is empty. Is this because Binance doesn't give back a trading account id?

**Comment by Vasile-Peste** [comment]
> Also one side note I noticed that the MidaTradingAccount id of a Binance/Spot account is empty. Is this because Binance doesn't give back a trading account id?

Yes, in Binance unfortunately the API will not report the user id so in this specific case it's going to be empty.
