### ISSUE TITLE
Closed Position Detail

### ISSUE THREAD

**Issue by desoss** [Reiryoku-Technologies/Mida#75]
I want to retrieve the net profit and possibly the account balance of an executed trade.

According to the documentation, I should find them in the [protooaclosepositiondetail](https://help.ctrader.com/open-api/symbol-data/#protooaclosepositiondetail) object contained in a trade.

Nevertheless, I haven't found a way to get this information.

**Comment by desoss** [comment]
Should I move this issue to [Mida-cTrader](https://github.com/Reiryoku-Technologies/Mida-cTrader)?

**Comment by Vasile-Peste** [comment]
I will close here since I have already answered in https://github.com/Reiryoku-Technologies/Mida/issues/76.

**Comment by desoss** [comment]
Notice that this should be related to [Reiryoku-Technologies/Mida-cTrader#36](https://github.com/Reiryoku-Technologies/Mida-cTrader/issues/36)not to the one that you've linked.
