### ISSUE TITLE
Can Mida introduce and use it in react?

### ISSUE THREAD

**Issue by huming1103** [Reiryoku-Technologies/Mida#90]
![微信图片_20230228143445](https://user-images.githubusercontent.com/30184067/221773425-e609ef5c-f6e3-487b-9608-84d0d98e8f22.png) I use the command npm install mida, install ctrader plug-in, and report an error in the browser after running
![error](https://user-images.githubusercontent.com/30184067/221773450-74dbca2c-32ef-49d8-b3d7-69819b70b741.png)

**Comment by Vasile-Peste** [comment]
Hello, there is no browser support, we highly recommend to setup Mida on a Node.js server and then requesting it's API from your separate frontend React application.

However Mida can be easily used in a browser if you remove the Node.js file system and crypto dependencies (you can easily replace them with some other alternatives).

Thank you!
