### ISSUE TITLE
Closed Position Detail

### ISSUE THREAD

**Issue by desoss** [Reiryoku-Technologies/Mida#95]
I want to retrieve the net profit and possibly the account balance of an executed trade.

According to the cTrader documentation, they should be contained in the [protooaclosepositiondetail](https://help.ctrader.com/open-api/symbol-data/#protooaclosepositiondetail) object contained in a trade.

Nevertheless, this object is not there in this plugin.

**Comment by Vasile-Peste** [comment]
To retrieve profits it's necessary to retrieve all trades and filter them by position id, if this is not enough, please create another issue indicating the exact information that you need to retrieve and how the current API is not allowing you to do so

Reference
https://www.mida.org/documentation/trades/trade.html
