### ISSUE TITLE
The cTrader getOrders function return only 5 entries

### ISSUE THREAD

**Issue by desoss** [Reiryoku-Technologies/Mida#97]
With the latest Mida version _2023.1.1_  the getOrders or the getTrades functions return only the latest 5 results.
This is not what was happening when I was using the CTraderPlugin.

Is it possible to have more results? Or even better to specify the period for the getOrders or the getTrades.

**Comment by Vasile-Peste** [comment]
Addressed in [2023.1.2](https://github.com/Reiryoku-Technologies/Mida/releases/tag/v2023.1.2).
Thank you for the report!
